apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: https-reencrypt
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: https-reencrypt
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/haahaakon/backendtlspolicy-app
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
