apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-custom
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/haahaakon/k8s-envoy-gateway-custom
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
