apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
  annotations:
    # wave 2: applied after the cert-manager chart (wave 1) is synced and its CRDs exist
    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    email: acme@lo0.no # TODO: replace with your email
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-dns-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
